// <auto-generated />
using System;
using Castr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Castr.Data.Migrations
{
    [DbContext(typeof(CastrDbContext))]
    [Migration("20260214213839_AddEpisodeFileMetadata")]
    partial class AddEpisodeFileMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Castr.Data.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("activity_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<int?>("FeedId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("feed_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType")
                        .HasDatabaseName("idx_activity_type");

                    b.HasIndex("FeedId", "CreatedAt")
                        .HasDatabaseName("idx_activity_feed_created");

                    b.ToTable("activity_log", (string)null);
                });

            modelBuilder.Entity("Castr.Data.Entities.DownloadQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("FeedId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("feed_id");

                    b.Property<int>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("progress_percent");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("queued_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("video_id");

                    b.Property<string>("VideoTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("video_title");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_queue_status");

                    b.HasIndex("FeedId", "Status")
                        .HasDatabaseName("idx_queue_feed_status");

                    b.HasIndex("FeedId", "VideoId")
                        .IsUnique()
                        .HasDatabaseName("idx_queue_feed_video");

                    b.ToTable("download_queue", (string)null);
                });

            modelBuilder.Entity("Castr.Data.Entities.DownloadedVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("downloaded_at");

                    b.Property<int>("FeedId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("feed_id");

                    b.Property<string>("Filename")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("video_id");

                    b.HasKey("Id");

                    b.HasIndex("FeedId", "VideoId")
                        .IsUnique()
                        .HasDatabaseName("idx_downloaded_feed_video");

                    b.ToTable("downloaded_videos", (string)null);
                });

            modelBuilder.Entity("Castr.Data.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_order");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("FeedId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("feed_id");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("filename");

                    b.Property<double?>("MatchScore")
                        .HasColumnType("REAL")
                        .HasColumnName("match_score");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("publish_date");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("VideoId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("video_id");

                    b.Property<string>("YoutubeTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("youtube_title");

                    b.HasKey("Id");

                    b.HasIndex("FeedId")
                        .HasDatabaseName("idx_episodes_feed_id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("idx_episodes_video_id");

                    b.HasIndex("FeedId", "DisplayOrder")
                        .HasDatabaseName("idx_episodes_display_order");

                    b.HasIndex("FeedId", "Filename")
                        .IsUnique()
                        .HasDatabaseName("idx_episodes_filename");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("Castr.Data.Entities.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("author");

                    b.Property<int>("CacheDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5)
                        .HasColumnName("cache_duration_minutes");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("directory");

                    b.Property<string>("FileExtensions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_extensions")
                        .HasDefaultValueSql("'.mp3'");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en-us")
                        .HasColumnName("language");

                    b.Property<string>("Link")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("YouTubeAudioQuality")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("highest")
                        .HasColumnName("youtube_audio_quality");

                    b.Property<bool>("YouTubeEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("youtube_enabled");

                    b.Property<int>("YouTubeMaxConcurrentDownloads")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("youtube_max_concurrent_downloads");

                    b.Property<string>("YouTubePlaylistUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("youtube_playlist_url");

                    b.Property<int>("YouTubePollIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(60)
                        .HasColumnName("youtube_poll_interval_minutes");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_feeds_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_feeds_name");

                    b.ToTable("feeds", (string)null);
                });

            modelBuilder.Entity("Castr.Data.Entities.ActivityLog", b =>
                {
                    b.HasOne("Castr.Data.Entities.Feed", "Feed")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("Castr.Data.Entities.DownloadQueueItem", b =>
                {
                    b.HasOne("Castr.Data.Entities.Feed", "Feed")
                        .WithMany("DownloadQueue")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("Castr.Data.Entities.DownloadedVideo", b =>
                {
                    b.HasOne("Castr.Data.Entities.Feed", "Feed")
                        .WithMany("DownloadedVideos")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("Castr.Data.Entities.Episode", b =>
                {
                    b.HasOne("Castr.Data.Entities.Feed", "Feed")
                        .WithMany("Episodes")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("Castr.Data.Entities.Feed", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("DownloadQueue");

                    b.Navigation("DownloadedVideos");

                    b.Navigation("Episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
